<?php

namespace Auth;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AdminTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=RoleSeeder');
    }

    public function test_users_screen_can_be_rendered()
    {
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get('/admin');

        $response->assertStatus(200);
    }

    public function test_users_can_be_updated()
    {
        $user = User::factory()->create();
        $user2=User::factory()->create();

        $response = $this->actingAs($user)->patch(route('admin.update',$user2));

        $response->assertRedirect();

        $response = $this->actingAs($user)->patch(route('admin.update',$user2));

        $response->assertRedirect();
    }

    public function test_products_can_be_deleted()
    {
        $user = User::factory()->create();
        $user2=User::factory()->create();

        $response = $this->actingAs($user)->delete(route('admin.destroy',$user2));
        $response->assertRedirect();
    }
}
